### ISSUE TITLE
Discovered feature not working even 1seconde

### ISSUE THREAD

**Issue by NagNag73** [vosmont/Vera-Plugin-ZiGateGateway#1]
Hi,

I have a vera edge using firmware 1.7.3500.
I also have a zigate using firmware ZiGate_Coordinator_v3.0b

Yesterday was my first attempt to use the zigate usbkey and discover aqara xiaomi devices. And yesterday the "discovered feature" of your plugin seemed to work as I could see it was in search mode during 30 secondes. It didn't find devices but at least it was searching.
Today I have updated my vera edge to the version I wrote above and since that the discovered button dosesn't put your plugin in search mode at all.
I tried to unplug and plug again the zigate. I switched off the vera and switched on again ...
But nothing works.

So until that discovered button works again I guess I won't be able to use my aqara devices with the vera.
If you could have a look at it it will be nice.
Until that I ll try to use the zigate directly on windows to check out if the key is alright.

Best Regards

Naguy

**Comment by vosmont** [comment]
Hello Naguy,

it seems that the firmware 1.7.3500 has broken the javascript Vera API.
Please use the plugin ALTUI on your Vera, and you will be able to use the ZiGate plugin.

Regards,
Vincent
