### ISSUE TITLE
Language file failed

### ISSUE THREAD

**Issue by physiker123** [vosmont/Vera-Plugin-ZiGateGateway#3]
Hello,

I just bought a zigate and installed it. Since my Vera's language is German, Vera hat troubles finding the right language filed. I copied the english one and replaced the "en" with "de". Perhaps there should be more languages available (or a check, which language is used, and if not present, use the english one).

Best regards!

**Comment by vosmont** [comment]
Hello @physiker123 ,
I thought that the Vera returns a 404 when a file does not exist... in fact it returns an empty file.
It will be fixed in the next release.

Thanks !

**Comment by physiker123** [comment]
Great, thank you very much!

**Comment by vosmont** [comment]
It should be fixed in the development branch

**Comment by physiker123** [comment]
Hi,

I just installed the development branch (I just copied the luup-files).

The startup is working (although I did not delete my -de file..).

When I want to go to the discovered devices tab, there is an error:

Error executing function ZiGateGateway.showEquipments(): ZiGateGateway.showDiscoveredDevices is not a function


It then switches to the managed equipments tab.

**Comment by physiker123** [comment]
I deleted the german file, now it shows the discovered devices tab. For the Problems please have a Look at the Other issue . Thank you anyway!
