### ISSUE TITLE
Aqara Temperature sensor not showing the values

### ISSUE THREAD

**Issue by weblikero** [vosmont/Vera-Plugin-ZiGateGateway#7]
I have added 1 Aqara temperature sensor https://www.youtube.com/watch?v=iBhPknNF1yU

, but the values of humidity and temparature values are always on zero. https://ibb.co/jj7zN0

**Comment by vosmont** [comment]
Hello @weblikero,
have you installed the version in the development branch ?

**Comment by weblikero** [comment]
Yes, latest version(this evening)

**Comment by vosmont** [comment]
It should work. You don't have a pressure sensor with your Aqara temperature sensor ?
Have you reload the Luup engine ?

**Comment by weblikero** [comment]
When I upload the loop files the "Restart Luup after upload" is checked.

**Comment by vosmont** [comment]
Can you provide some logs ? (You will see how to do in the project presentation)

**Comment by weblikero** [comment]
root@MiOS_5016:/# tail -F /var/log/cmh/LuaUPnP.log | grep "ERROR\|ZiGateGateway"
02      11/16/18 20:02:33.239   luup_log:18: (ZiGateGateway::Network.receive)              Attribute Report: (address:27AB),(endpointId:01),(cluster:0403) - (attrId:0014) is not handled <0x73992520>
02      11/16/18 20:02:33.240   luup_log:18: (ZiGateGateway::Network.receive)              Problem with message (type:8102), (payload:8827AB010403001400280001FF) <0x73992520>
02      11/16/18 20:02:33.245   luup_log:18: (ZiGateGateway::Network.receive)              Attribute Report: (address:27AB),(endpointId:01),(cluster:0403) - (attrId:0010) is not handled <0x73992520>
02      11/16/18 20:02:33.245   luup_log:18: (ZiGateGateway::Network.receive)              Problem with message (type:8102), (payload:8827AB0104030010002900022793) <0x73992520>

**Comment by weblikero** [comment]
It works with latest development version
